### ISSUE TITLE
Change Link to production

### ISSUE THREAD

**Issue by isnuryusuf** [BiznetGIO/neolite#1]
https://github.com/BiznetGIO/neolite/blob/789fffe2f0701627ccd7f3ecde93f1990646d926/examples/create_vm.rs#L79C16-L79C60

**Comment by azzamsa** [comment]
Hi there,

- The code you mentioned will not be included in any of the releases. It's there to demonstrate the usage of this SDK.
- Hardcoding the URL was intentional from the start, as using environment variables would add unnecessary complexity to the demo.
- Exposing the URL doesn't pose any harm, as any action requires authentication.
- There is no official release for the SDK (yet), so it will be faster to iterate by just running the example repeatedly.

Thank you for stopping by.
